# Generated by Django 4.2.2 on 2024-06-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published_status', 'Can publish product'), ('chenge_description', 'Can change product description'), ('chenge_category', 'Can change product category')], 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукции'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
    ]
